### PR TITLE
Game over base implementation

### PR DESCRIPTION
**Pull request by feenkind**
Umbau zur MVVM Struktur, ähnlich https://github.com/TroelsMortensen/Battleship.
Die Applikation zeigt jetzt einen Countdown an, der von 30 Sekunden runterzählt. 
Die Implementierung des Modals wäre dann Teil des nächsten PRs

### CODE REVIEW

**Comment by wernerbreitenstein** [comment]
What about renaming the start-Method in ViewHandler.java to run() or something equivalent, just to avoid that one start-Method invokes another one?

Shouldn't  the Constructor of the ViewHandler have a Stage-Object as an Argument to allow switching to other views in the same window lateron.

Please move the statement in ViewHandler in line 22 to line 35 to keep things together.

The openLevelView-Method might be nicer if it could receive an argument and therefore select several different views (see Video Part 4 at about 0:55:40).

**Comment by feenkind** [comment]
> What about renaming the start-Method in ViewHandler.java to run() or something equivalent, just to avoid that one start-Method invokes another one?

I'm not quite sure if I get what you mean? It runs the `show()` method of the stage?
> 
> Shouldn't the Constructor of the ViewHandler have a Stage-Object as an Argument to allow switching to other views in the same window lateron.
We are only working with one stage (one window) for now, so I'd just add it later if we really need it? I thought the argument would be needed if we have different windows, but maybe I misunderstood?
> 
> Please move the statement in ViewHandler in line 22 to line 35 to keep things together.
The `show()` method will be executed for every view that is loaded with `start()`. In order to avoid redundant code I think it's fine in the `start()` method - it also refers to the scene of this class. (see also https://github.com/TroelsMortensen/Battleship/blob/master/src/client/core/ViewHandler.java#L24)
> 
> The openLevelView-Method might be nicer if it could receive an argument and therefore select several different views (see Video Part 4 at about 0:55:40).
That might be nice for the different levels, true. Should I add it already or do we do it when we really have the different levels?

**Comment by wernerbreitenstein** [comment]
> > What about renaming the start-Method in ViewHandler.java to run() or something equivalent, just to avoid that one start-Method invokes another one?
> 
> I'm not quite sure if I get what you mean? It runs the `show()` method of the stage?

OK, my mistake, sorry. I referred to line 17 in FrisbeeApp.java (not in ViewHandler.java) where the ViewHandler is invoked. I think it's quite odd to call a start-Method in another one called start-Method.
> 
> > Shouldn't the Constructor of the ViewHandler have a Stage-Object as an Argument to allow switching to other views in the same window lateron.
> 
> We are only working with one stage (one window) for now, so I'd just add it later if we really need it? I thought the argument would be needed if we have different windows, but maybe I misunderstood?
> 
> > Please move the statement in ViewHandler in line 22 to line 35 to keep things together.
> 
> The `show()` method will be executed for every view that is loaded with `start()`. In order to avoid redundant code I think it's fine in the `start()` method - it also refers to the scene of this class. (see also https://github.com/TroelsMortensen/Battleship/blob/master/src/client/core/ViewHandler.java#L24)
> 
> > The openLevelView-Method might be nicer if it could receive an argument and therefore select several different views (see Video Part 4 at about 0:55:40).
> 
> That might be nice for the different levels, true. It's added.

**Comment by feenkind** [comment]
> > > What about renaming the start-Method in ViewHandler.java to run() or something equivalent, just to avoid that one start-Method invokes another one?
> > 
> > 
> > I'm not quite sure if I get what you mean? It runs the `show()` method of the stage?
> 
> OK, my mistake, sorry. I referred to line 17 in FrisbeeApp.java (not in ViewHandler.java) where the ViewHandler is invoked. I think it's quite odd to call a start-Method in another one called start-Method.

Ah okay - well I don't think it's odd, but I don't have a strong opinion on that. If you are bothered by it, I can rename it.

**Comment by wernerbreitenstein** [comment]
> > > > What about renaming the start-Method in ViewHandler.java to run() or something equivalent, just to avoid that one start-Method invokes another one?
> > > 
> > > 
> > > I'm not quite sure if I get what you mean? It runs the `show()` method of the stage?
> > 
> > 
> > OK, my mistake, sorry. I referred to line 17 in FrisbeeApp.java (not in ViewHandler.java) where the ViewHandler is invoked. I think it's quite odd to call a start-Method in another one called start-Method.
> 
> Ah okay - well I don't think it's odd, but I don't have a strong opinion on that. It might make sense, because it "continues" the application start method (with setting the stage, etc). But if you are bothered by it, I can rename it.

OK, that's a point. Leave it unchanged then. It's a minor issue anyway.

**Review by wernerbreitenstein — APPROVED** [review]

**Review by D1ANAmic — APPROVED** [review]

**Pull request merged**
